import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./lib/StoreProvider";
import { store } from "./lib/store";
import NavBarMenu from "./components/NavBar/NavBar";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <StoreProvider children={store}>
        <body className={inter.className}>
          <Toaster position="top-center" reverseOrder={false} />
          <NavBarMenu />
          {children}
        </body>
      </StoreProvider>
    </html>
  );
}
